### ISSUE TITLE
typo : hasing

### ISSUE THREAD

**Issue by grempe** [dahlia/json-hash#3]
See:

https://github.com/dahlia/json-hash#digestts-hasing-json-entities

replace 'hasing' with 'hashing'

**Comment by grempe** [comment]
See also first line of that section:

> This module is a thing wrapper around the above canonicalize() function and the curated collection of cryptographic hash algorithms:

replace 'thing' with 'thin'

**Comment by dahlia** [comment]
Thank you for reporting!
